name: build plugin

on: [push]

jobs:
  build-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: ./configure.sh
      - name: install protoc
        run: sudo cp -R ./protoc /usr/local
      - name: install
        run: |
          mkdir -p build
          cd build || exit
          cmake ..
          make
      - name: Upload Linux
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v1
        with:
          name: protoc-gen-java-leo-linux
          path: ./build/protoc-gen-java-leo
      - name: Upload Macos
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v1
        with:
          name: protoc-gen-java-leo-osx
          path: ./build/protoc-gen-java-leo
  build-windows:
    #if: startsWith(github.ref, 'disabled')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: |
          $latestProtocRelease = Get-Content fetch/protoc_release.txt -First 1
          $url="https://github.com/leohilbert/protobuf-compile/releases/download/$latestProtocRelease/protoc-$latestProtocRelease-windows.zip"
          Write-Output "Downloading $url"
          Invoke-WebRequest -uri $url -outfile protoc.zip
          Expand-Archive protoc.zip protoc
      - uses: ilammy/msvc-dev-cmd@v1
      - name: install
        run: |
          mkdir -p build
          cd build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          nmake
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: protoc-gen-java-leo-windows
          path: ./build/protoc-gen-java-leo.exe
  docker-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@master
      - name: publish
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'protoc-gen-java-leo'
          TAG: 'latest'
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-deploy-jar:
    needs: build-unix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - uses: actions/download-artifact@v1
        with:
          name: protoc-gen-java-leo-linux
          path: ./build/
      - name: build jar
        run: |
          ./configure.sh
          chmod +x ./build/protoc-gen-java-leo
          sudo cp -R protoc/** /usr/local
          sudo ldconfig
      - name: maven test
        run: cd java && mvn clean test
      - name: maven deploy
        if: github.ref == 'refs/heads/master'
        uses: samuelmeuli/action-maven-publish@v1
        with:
          directory: java
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
      - name: Upload jar artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: protoc-gen-java-leo-jar
          path: ./java/target/protobuf-java-leo.jar
  deploy-exe:
    if: github.ref == 'refs/heads/master'
    needs: [test-deploy-jar, build-unix, build-windows]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        classifier: [linux, osx, windows]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: protoc-gen-java-leo-${{ matrix.classifier }}
          path: ./executable
      - name: exe deploy preparations
        run: |
          mv $(find executable -type f) executable/exe
          chmod +x ./gpghack.sh
      - name: maven deploy
        uses: leohilbert/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_PASSWORD }}
          maven_goals_phases: gpg:sign-and-deploy-file
          maven_args: >
            -DpomFile=java/pom.xml -Dfile=./executable/exe
            -Durl=https://oss.sonatype.org/content/repositories/snapshots -Dclassifier=${{ matrix.classifier }}
            -DrepositoryId=ossrh -Dpackaging=exe -Dgpg.executable="./gpghack.sh" -DupdateReleaseInfo=true